-- Rotorflight Tuning DB schema
-- All PKs/FKs stored as TEXT (UUIDs generated by Python, not DB)
-- Runs once on first container start via docker-entrypoint-initdb.d

CREATE TABLE IF NOT EXISTS flights (
    id               TEXT PRIMARY KEY,
    name             TEXT NOT NULL,
    craft_name       TEXT,
    flown_at         TIMESTAMPTZ,
    csv_filename     TEXT,
    csv_path         TEXT,
    total_loop_iterations BIGINT,
    sample_rate_hz   FLOAT,
    duration_s       FLOAT,
    firmware_version TEXT,
    board_name       TEXT,
    notes            TEXT,
    created_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS segments (
    id               TEXT PRIMARY KEY,
    flight_id        TEXT NOT NULL REFERENCES flights(id) ON DELETE CASCADE,
    label            TEXT NOT NULL,
    start_iteration  BIGINT,
    end_iteration    BIGINT,
    csv_path         TEXT,
    row_count        INTEGER,
    notes            TEXT,
    analysis_status  TEXT DEFAULT 'pending',
    created_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS segment_metrics (
    id           TEXT PRIMARY KEY,
    segment_id   TEXT NOT NULL REFERENCES segments(id) ON DELETE CASCADE,
    module       TEXT NOT NULL,
    metric_name  TEXT NOT NULL,
    value_float  FLOAT,
    value_json   JSONB,
    unit         TEXT,
    computed_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_metrics_segment ON segment_metrics(segment_id);
CREATE INDEX IF NOT EXISTS idx_metrics_module  ON segment_metrics(segment_id, module);

CREATE TABLE IF NOT EXISTS config_dumps (
    id           TEXT PRIMARY KEY,
    flight_id    TEXT REFERENCES flights(id) ON DELETE CASCADE,
    raw_text     TEXT,
    craft_name   TEXT,
    firmware     TEXT,
    created_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pid_profiles (
    id             TEXT PRIMARY KEY,
    config_dump_id TEXT NOT NULL REFERENCES config_dumps(id) ON DELETE CASCADE,
    profile_index  INTEGER NOT NULL,
    target_rpm     INTEGER,
    roll_p INTEGER,  roll_i  INTEGER, roll_d  INTEGER, roll_f  INTEGER,
    pitch_p INTEGER, pitch_i INTEGER, pitch_d INTEGER, pitch_f INTEGER,
    yaw_p INTEGER,   yaw_i  INTEGER,  yaw_d  INTEGER,  yaw_f  INTEGER,
    roll_gyro_cutoff  INTEGER,
    pitch_gyro_cutoff INTEGER,
    yaw_gyro_cutoff   INTEGER,
    gov_p INTEGER, gov_i INTEGER, gov_f INTEGER,
    is_active BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS rate_profiles (
    id             TEXT PRIMARY KEY,
    config_dump_id TEXT NOT NULL REFERENCES config_dumps(id) ON DELETE CASCADE,
    profile_index  INTEGER NOT NULL,
    roll_rc_rate   FLOAT, roll_srate  FLOAT, roll_expo  FLOAT,
    pitch_rc_rate  FLOAT, pitch_srate FLOAT, pitch_expo FLOAT,
    yaw_rc_rate    FLOAT, yaw_srate   FLOAT, yaw_expo   FLOAT
);

CREATE TABLE IF NOT EXISTS filter_settings (
    id              TEXT PRIMARY KEY,
    config_dump_id  TEXT NOT NULL REFERENCES config_dumps(id) ON DELETE CASCADE,
    lpf1_type       TEXT, lpf1_hz    INTEGER,
    lpf2_type       TEXT, lpf2_hz    INTEGER,
    dyn_notch_count INTEGER, dyn_notch_q INTEGER,
    dyn_notch_min_hz INTEGER, dyn_notch_max_hz INTEGER,
    rpm_filter_enabled BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS ai_analyses (
    id                TEXT PRIMARY KEY,
    segment_id        TEXT NOT NULL REFERENCES segments(id) ON DELETE CASCADE,
    model_used        TEXT,
    narrative         TEXT,
    structured_output JSONB,
    status            TEXT DEFAULT 'pending',
    requested_at      TIMESTAMPTZ DEFAULT NOW(),
    completed_at      TIMESTAMPTZ
);
